//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/_OperationCheckout/_Scripts/P2InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @P2InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @P2InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""P2InputControls"",
    ""maps"": [
        {
            ""name"": ""ShoppingCart"",
            ""id"": ""4ab35e61-dd89-4777-aebe-d1bbb6f80a77"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5ca5e7c4-1955-44a7-bd7e-5a285871a3fd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ram"",
                    ""type"": ""Button"",
                    ""id"": ""d6301edc-3230-467a-b269-e947d22ad78f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blast"",
                    ""type"": ""Button"",
                    ""id"": ""23e3541f-058e-4eca-b565-d120013cccd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""6aea69d0-fa22-4bb9-8ca8-6f4dc4b46dd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""5cbd04b6-e9aa-4e7e-ae49-a792543b3068"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""0a5e3c65-2e83-4799-8de8-68b2f2895a3f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e65e5f56-b6c5-4f02-806a-9dce3c815e34"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""977e2971-1206-4ec3-80da-1cfaa3f0541a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c57d7522-1031-4952-ac1b-4c77c9ef4c5a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e8b066d1-3395-432a-9c71-9869212aeaed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e5aa49b6-33ac-4013-a857-7e8026fab5d5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad18b927-6a8a-4d9e-ba1a-d49d31e8e9e1"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ram"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f068f03-0e6e-4dcd-bb00-25b35d590dc5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ram"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad64b857-5be1-4d14-b3d4-6e891c825965"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ram"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b19d50d2-3187-4e27-b585-8e27e77b703a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6b156a8-6bea-42fd-aeca-dcc052fb44ed"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a193addd-a8d6-4c63-a56f-540bdd409f97"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b44b2513-375d-4f9a-bd25-8f47bd927c0c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81f1daf0-04f1-4606-a93d-379ea7b1fb45"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cec29fc1-9ec1-4b8b-8a93-6033e224be1c"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ShoppingCart
        m_ShoppingCart = asset.FindActionMap("ShoppingCart", throwIfNotFound: true);
        m_ShoppingCart_Movement = m_ShoppingCart.FindAction("Movement", throwIfNotFound: true);
        m_ShoppingCart_Ram = m_ShoppingCart.FindAction("Ram", throwIfNotFound: true);
        m_ShoppingCart_Blast = m_ShoppingCart.FindAction("Blast", throwIfNotFound: true);
        m_ShoppingCart_Pause = m_ShoppingCart.FindAction("Pause", throwIfNotFound: true);
        m_ShoppingCart_Dash = m_ShoppingCart.FindAction("Dash", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ShoppingCart
    private readonly InputActionMap m_ShoppingCart;
    private List<IShoppingCartActions> m_ShoppingCartActionsCallbackInterfaces = new List<IShoppingCartActions>();
    private readonly InputAction m_ShoppingCart_Movement;
    private readonly InputAction m_ShoppingCart_Ram;
    private readonly InputAction m_ShoppingCart_Blast;
    private readonly InputAction m_ShoppingCart_Pause;
    private readonly InputAction m_ShoppingCart_Dash;
    public struct ShoppingCartActions
    {
        private @P2InputControls m_Wrapper;
        public ShoppingCartActions(@P2InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_ShoppingCart_Movement;
        public InputAction @Ram => m_Wrapper.m_ShoppingCart_Ram;
        public InputAction @Blast => m_Wrapper.m_ShoppingCart_Blast;
        public InputAction @Pause => m_Wrapper.m_ShoppingCart_Pause;
        public InputAction @Dash => m_Wrapper.m_ShoppingCart_Dash;
        public InputActionMap Get() { return m_Wrapper.m_ShoppingCart; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShoppingCartActions set) { return set.Get(); }
        public void AddCallbacks(IShoppingCartActions instance)
        {
            if (instance == null || m_Wrapper.m_ShoppingCartActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShoppingCartActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Ram.started += instance.OnRam;
            @Ram.performed += instance.OnRam;
            @Ram.canceled += instance.OnRam;
            @Blast.started += instance.OnBlast;
            @Blast.performed += instance.OnBlast;
            @Blast.canceled += instance.OnBlast;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
        }

        private void UnregisterCallbacks(IShoppingCartActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Ram.started -= instance.OnRam;
            @Ram.performed -= instance.OnRam;
            @Ram.canceled -= instance.OnRam;
            @Blast.started -= instance.OnBlast;
            @Blast.performed -= instance.OnBlast;
            @Blast.canceled -= instance.OnBlast;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
        }

        public void RemoveCallbacks(IShoppingCartActions instance)
        {
            if (m_Wrapper.m_ShoppingCartActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShoppingCartActions instance)
        {
            foreach (var item in m_Wrapper.m_ShoppingCartActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShoppingCartActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShoppingCartActions @ShoppingCart => new ShoppingCartActions(this);
    public interface IShoppingCartActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRam(InputAction.CallbackContext context);
        void OnBlast(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
    }
}
